### ISSUE TITLE
Notebook CI test fails with `kernel died`

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/xbitinfo#212]
### Description

The following error is currently raised in the `test_notebook` CI job:

```
[NbConvertApp] ERROR | Kernel died while waiting for execute reply.
[21](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:22)
Traceback (most recent call last):
[22](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:23)
  File "/usr/share/miniconda3/envs/bitinfo/bin/jupyter-nbconvert", line 10, in <module>
[23](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:24)
    sys.exit(main())
[24](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:25)
             ^^^^^^
[25](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:26)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/jupyter_core/application.py", line 277, in launch_instance
[26](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:27)
    return super().launch_instance(argv=argv, **kwargs)
[27](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:28)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[28](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:29)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/traitlets/config/application.py", line 1043, in launch_instance
[29](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:30)
    app.start()
[30](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:31)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 414, in start
[31](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:32)
    self.convert_notebooks()
[32](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:33)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 589, in convert_notebooks
[33](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:34)
    self.convert_single_notebook(notebook_filename)
[34](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:35)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 555, in convert_single_notebook
[35](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:36)
    output, resources = self.export_single_notebook(
[36](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:37)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[37](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:38)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 481, in export_single_notebook
[38](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:39)
    output, resources = self.exporter.from_filename(
[39](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:40)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[40](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:41)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 388, in from_filename
[41](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:42)
    return super().from_filename(filename, resources, **kw)  # type:ignore
[42](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:43)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[43](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:44)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 201, in from_filename
[44](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:45)
    return self.from_file(f, resources=resources, **kw)
[45](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:46)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[46](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:47)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 394, in from_file
[47](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:48)
    return super().from_file(file_stream, resources, **kw)  # type:ignore
[48](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:49)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[49](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:50)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 220, in from_file
[50](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:51)
    return self.from_notebook_node(
[51](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:52)
           ^^^^^^^^^^^^^^^^^^^^^^^^
[52](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:53)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/exporters/html.py", line 234, in from_notebook_node
[53](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:54)
    return super().from_notebook_node(nb, resources, **kw)
[54](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:55)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[55](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:56)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 410, in from_notebook_node
[56](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:57)
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
[57](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:58)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[58](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:59)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 154, in from_notebook_node
[59](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:60)
    nb_copy, resources = self._preprocess(nb_copy, resources)
[60](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:61)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[61](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:62)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 352, in _preprocess
[62](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:63)
    nbc, resc = preprocessor(nbc, resc)
[63](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:64)
                ^^^^^^^^^^^^^^^^^^^^^^^
[64](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:65)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/preprocessors/base.py", line 48, in __call__
[65](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:66)
    return self.preprocess(nb, resources)
[66](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:67)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[67](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:68)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/preprocessors/execute.py", line 100, in preprocess
[68](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:69)
    self.preprocess_cell(cell, resources, index)
[69](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:70)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbconvert/preprocessors/execute.py", line 121, in preprocess_cell
[70](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:71)
    cell = self.execute_cell(cell, index, store_history=True)
[71](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:72)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[72](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:73)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
[73](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:74)
    return loop.run_until_complete(inner)
[74](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:75)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[75](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:76)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
[76](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:77)
    return future.result()
[77](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:78)
           ^^^^^^^^^^^^^^^
[78](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:79)
  File "/usr/share/miniconda3/envs/bitinfo/lib/python3.11/site-packages/nbclient/client.py", line 1005, in async_execute_cell
[79](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:80)
    raise DeadKernelError("Kernel died") from None
[80](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:81)
nbclient.exceptions.DeadKernelError: Kernel died
[81](https://github.com/observingClouds/xbitinfo/actions/runs/5229009356/jobs/9441730211#step:8:82)
Error: Process completed with exit code 1.
```

**Comment by observingClouds** [comment]
Looking into this a bit closer it seems to be connected with the GIL and occurs when the entire notebook already run and is shutdown. I can reproduce the error by simply doing `import xbitinfo as xb` in a notebook and then restart the kernel. When I restart the kernel the following error message occurs:

```
[58373] signal (15): Terminated: 15
in expression starting at none:0
kevent at /usr/lib/system/libsystem_kernel.dylib (unknown line)
select_kqueue_control_impl at /Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/lib-dynload/select.cpython-311-darwin.so (unknown line)
_PyEval_EvalFrameDefault at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
_PyEval_Vector at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
PyEval_EvalCode at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
builtin_exec at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
cfunction_vectorcall_FASTCALL_KEYWORDS at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
_PyEval_EvalFrameDefault at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
_PyFunction_Vectorcall at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
pymain_run_module at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
Py_RunMain at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
main at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
start at /usr/lib/dyld (unknown line)
unknown function (ip: 0x0)
Allocations: 42521433 (Pool: 42488231; Big: 33202); GC: 58
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized

Thread 0x0000700014478000 (most recent call first):
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/ipykernel/parentpoller.py", line 40 in run
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x00007000133f2000 (most recent call first):
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 320 in wait
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 622 in wait
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/IPython/core/history.py", line 884 in run
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/IPython/core/history.py", line 60 in only_when_enabled
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/decorator.py", line 232 in fun
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x00007000123ef000 (most recent call first):
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/selectors.py", line 561 in select
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/asyncio/base_events.py", line 1884 in _run_once
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/asyncio/base_events.py", line 607 in run_forever
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195 in start
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/ipykernel/control.py", line 23 in run
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x00007000113ec000 (most recent call first):
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/ipykernel/iostream.py", line 374 in _watch_pipe_fd
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 975 in run
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x00007000103e9000 (most recent call first):
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/ipykernel/iostream.py", line 370 in _watch_pipe_fd
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 975 in run
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x000070000f2e0000 (most recent call first):
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/ipykernel/heartbeat.py", line 106 in run
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x000070000e2dd000 (most recent call first):
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/selectors.py", line 561 in select
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/asyncio/base_events.py", line 1884 in _run_once
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/asyncio/base_events.py", line 607 in run_forever
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195 in start
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/ipykernel/iostream.py", line 84 in _thread_main
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 975 in run
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/threading.py", line 995 in _bootstrap

Current thread 0x00007ff851517700 (most recent call first):
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/selectors.py", line 561 in select
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/asyncio/base_events.py", line 1884 in _run_once
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/asyncio/base_events.py", line 607 in run_forever
  File "/Users/haukeschulz/mambaforge/envs/bitinfo/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195 in start
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 728 in start
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/traitlets/config/application.py", line 1043 in launch_instance
  File "/Users/haukeschulz/.local/lib/python3.11/site-packages/ipykernel_launcher.py", line 17 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main

Extension modules: zmq.backend.cython.context, zmq.backend.cython.message, zmq.backend.cython.socket, zmq.backend.cython._device, zmq.backend.cython._poll, zmq.backend.cython._proxy_steerable, zmq.backend.cython._version, zmq.backend.cython.error, zmq.backend.cython.utils, tornado.speedups, psutil._psutil_osx, psutil._psutil_posix, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.ops, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.indexing, pandas._libs.index, pandas._libs.internals, pandas._libs.join, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, cftime._cftime, yaml._yaml, cytoolz.utils, cytoolz.itertoolz, cytoolz.functoolz, cytoolz.dicttoolz, cytoolz.recipes, markupsafe._speedups, numcodecs.compat_ext, numcodecs.blosc, numcodecs.zstd, numcodecs.lz4, numcodecs._shuffle, msgpack._cmsgpack, numcodecs.vlen, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver._cext (total: 83)

[58373] signal (6): Abort trap: 6
in expression starting at none:0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
pthread_kill at /usr/lib/system/libsystem_pthread.dylib (unknown line)
abort at /usr/lib/system/libsystem_c.dylib (unknown line)
fatal_error_exit at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
fatal_error at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
_Py_FatalErrorFunc at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
_Py_FatalError_TstateNULL at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
dict_dealloc at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
func_dealloc at /Users/haukeschulz/mambaforge/envs/bitinfo/bin/python3.11 (unknown line)
pydecref_ at /Users/haukeschulz/mambaforge/envs/bitinfo/share/julia/packages/PyCall/twYvK/src/PyCall.jl:118
pydecref at /Users/haukeschulz/mambaforge/envs/bitinfo/share/julia/packages/PyCall/twYvK/src/PyCall.jl:123
unknown function (ip: 0x1410b29b6)
ijl_apply_generic at /Users/haukeschulz/mambaforge/envs/bitinfo/lib/julia/libjulia-internal.1.9.dylib (unknown line)
run_finalizer at /Users/haukeschulz/mambaforge/envs/bitinfo/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_gc_run_finalizers_in_list at /Users/haukeschulz/mambaforge/envs/bitinfo/lib/julia/libjulia-internal.1.9.dylib (unknown line)
run_finalizers at /Users/haukeschulz/mambaforge/envs/bitinfo/lib/julia/libjulia-internal.1.9.dylib (unknown line)
ijl_atexit_hook at /Users/haukeschulz/mambaforge/envs/bitinfo/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_exit_thread0_cb at /Users/haukeschulz/mambaforge/envs/bitinfo/lib/julia/libjulia-internal.1.9.dylib (unknown line)
Allocations: 42521433 (Pool: 42488231; Big: 33202); GC: 58
```
